### ISSUE TITLE
SSO: The vendor application is verse of the day

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#395]
Do we need to create an app for zume, so that it doesn't throw anyone off as they are using the SSO

![Screenshot 2024-05-21 at 11 59 47 AM](https://github.com/ZumeProject/zume-training-system/assets/7318348/77858758-f804-471f-8776-be811c8b2e27)

**Comment by squigglybob** [comment]
yes we definitely should

**Comment by squigglybob** [comment]
This has been changed, to a zume version and now looks like this

![Image](https://github.com/ZumeProject/zume-training-system/assets/9816214/9c45ee92-c0d0-4565-978d-4846fe6a3875)

In order to make it say something without all the numbers.firebaseapp.com we would need to either
1. host zume with firebase, verify ownership of zume.training, use auth.zume.training as the redirect for SSO login
2. or get another domain name like zume-auth.training or something. (not sure i like this as it means more overhead and it still wouldn't  match zume.training correctly)
3. or leave it as it is, at least zume-project... is better than verse-of-the-day (we may be able to make it say zume-training, but might need a rejig to do so)
